### PR TITLE
test

### PR DESCRIPTION
**Pull request by msteckyefantis**

### CODE REVIEW

**Comment by SunNorth** [comment]
Hi Mike,
How is everything for you?

Here are some assets for your app. 
I did not make UI much, but maybe those will help you a little bit

Two primary colors :
#61B3BE
#FE8834

Background color :
#656776

Font: 
Archivo Bold (36px) for titles
Archivo SemiBold (28px) for text 
font-color: #1A2836 or white
background: #1A2836;


border-radius : 15

Icons:





I know it is not enough but I still hope it will help you. If you have any idea about your logo, just send it to me, I will draw it pixel-perfect.

Looking forward for your feedback.


Let me know please how are you?


Best,
Olesia

**Comment by msteckyefantis** [comment]
Hey Olesia,

Just saw this. I'm doing well thank you, how are you?

Colours and the other styles look like a good foundation, maybe the background is a bit dark, maybe it should be more colourful or cartoony, like a video game.

i don't know if you created any icons yet it just says "icons:"

anyways the logo should be an upside pyramid with an eye in the middle of it, like the one on the us dollar bill but the pyramid/triangle is flipped upside down.


let me know if you have any questions about it

**Comment by SunNorth** [comment]
Hi
That's interesting logo. I like it. I'll try to make it. Ok I got the idea
about light bg. To be honest I've never played in video games 😀. Have no
idea what is on trend. Let me know please

Olesia

**Comment by msteckyefantis** [comment]
I don't know if I should feel happy or sad for you that you've never played video games before😂

here are some classics:
dk
mario
sonic
zelda
and you can do a search of pokemon images to see the use of colours:
https://www.google.com/search?q=pokemon&rlz=1C5CHFA_enCA789CA790&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjt3bOcpLjiAhXNct8KHbN5Cz0Q_AUIDigB&biw=1680&bih=832&dpr=2

**Pull request merged**
